export enum ErrorCode {
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  AUTH_HEADER_MISSING = 'AUTH_HEADER_MISSING',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  FORBIDDEN = 'FORBIDDEN',

  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  DATABASE_ERROR = 'DATABASE_ERROR',
}
